version: "3.9.6"
# services:
#   apicode:
#     build: ./
#     environment:
#       - DOWNLOAD_PATH= ./
#       - CHROMEDRIVE_PATH=./helpers/cromedriver
#       - LC_ALL=C.UTF-8
#       - LANG=C.UTF-8
#     ports:
#       - '8000:8000'
#   selenium:
#     image: 'selenium/standalone-chrome'
#     ports:
#       - "4444:4444"
#       - "5900:5900"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - selenium
    environment:
      - SELENIUM_HOST=selenium
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]

  selenium:
    image: selenium/standalone-chrome